const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('lilac', {
  season: () => ipcRenderer.invoke('anime:season'),
  top: () => ipcRenderer.invoke('anime:top'),
  search: query => ipcRenderer.invoke('anime:search', query),
  detail: id => ipcRenderer.invoke('anime:detail', id),
  linkkfHome: (page = 1, limit = 20) => ipcRenderer.invoke('linkkf:home', page, limit),
  linkkfDetail: id => ipcRenderer.invoke('linkkf:detail', id),
  linkkfEpisodes: id => ipcRenderer.invoke('linkkf:episodes', id),
  linkkfPlay: episode => ipcRenderer.invoke('linkkf:play', episode),
  linkkfResolve: episode => ipcRenderer.invoke('linkkf:resolve', episode),
  linkkfSchedule: () => ipcRenderer.invoke('linkkf:schedule'),
  linkkfSections: () => ipcRenderer.invoke('linkkf:sections'),
  linkkfFilterTags: () => ipcRenderer.invoke('linkkf:filter-tags'),
  linkkfFilter: request => ipcRenderer.invoke('linkkf:filter', request),
  linkkfSearch: query => ipcRenderer.invoke('linkkf:search', query),
  linkkfExtras: anime => ipcRenderer.invoke('linkkf:extras', anime),
  linkkfRecordView: postId => ipcRenderer.invoke('linkkf:record-view', postId),
  providerCatalog: (provider, query = '', offset = 0) => ipcRenderer.invoke('provider:catalog', provider, query, offset),
  providerSeason: provider => ipcRenderer.invoke('provider:season', provider),
  providerAiring: provider => ipcRenderer.invoke('provider:airing', provider),
  providerDetail: anime => ipcRenderer.invoke('provider:detail', anime),
  providerPlay: (episode, title) => ipcRenderer.invoke('provider:play', episode, title),
  providerResolve: episode => ipcRenderer.invoke('provider:resolve', episode),
  providerSubtitleTracks: episode => ipcRenderer.invoke('provider:subtitle-tracks', episode),
  coverData: url => ipcRenderer.invoke('cover:data', url),
  opEdSkip: request => ipcRenderer.invoke('oped:get', request),
  clearOpEd: () => ipcRenderer.invoke('oped:clear'),
  onOpEdStatus: callback => ipcRenderer.on('oped:status', (_, message) => callback(message)),
  downloadMedia: (url, name) => ipcRenderer.invoke('media:download', url, name),
  onDownloadProgress: callback => ipcRenderer.on('download:progress', (_, value) => callback(value)),
  downloads: () => ipcRenderer.invoke('downloads:list'),
  addDownload: request => ipcRenderer.invoke('downloads:add', request),
  cancelDownload: id => ipcRenderer.invoke('downloads:cancel', id),
  resumeDownload: id => ipcRenderer.invoke('downloads:resume', id),
  removeDownload: id => ipcRenderer.invoke('downloads:remove', id),
  playDownload: id => ipcRenderer.invoke('downloads:play', id),
  openDownloadsFolder: () => ipcRenderer.invoke('downloads:open-folder'),
  downloadRoot: () => ipcRenderer.invoke('downloads:root'),
  chooseDownloadRoot: () => ipcRenderer.invoke('downloads:choose-root'),
  clearDownloads: () => ipcRenderer.invoke('downloads:clear'),
  onDownloadsChanged: callback => ipcRenderer.on('downloads:changed', (_, value) => callback(value)),
  findSubtitle: (source, title, episode, anime, options) => ipcRenderer.invoke('subtitle:find', source, title, episode, anime, options),
  anissiaMakers: (title, anime) => ipcRenderer.invoke('anissia:makers', title, anime),
  remoteSubtitle: (url, referer) => ipcRenderer.invoke('subtitle:remote', url, referer),
  savedSubtitles: key => ipcRenderer.invoke('subtitle-store:list', key),
  saveSubtitle: (key, entry) => ipcRenderer.invoke('subtitle-store:save', key, entry),
  removeSavedSubtitle: (key, id) => ipcRenderer.invoke('subtitle-store:remove', key, id),
  subtitleCacheUsage: () => ipcRenderer.invoke('subtitle-cache:usage'),
  cleanSubtitleCache: () => ipcRenderer.invoke('subtitle-cache:clean'),
  clearSubtitleCache: () => ipcRenderer.invoke('subtitle-cache:clear-all'),
  mpvStatus: () => ipcRenderer.invoke('mpv:status'),
  mpvPlay: (url, subtitlePath, title) => ipcRenderer.invoke('mpv:play', url, subtitlePath, title),
  setPlayerFullscreen: enabled => ipcRenderer.invoke('player:fullscreen', Boolean(enabled)),
  // Main returns {path,url}: url.pathToFileURL is unavailable in the sandboxed preload.
  chooseVideo: async () => (await ipcRenderer.invoke('file:video'))?.url || null,
  chooseSubtitle: async () => (await ipcRenderer.invoke('file:subtitle'))?.url || null,
  chooseSubtitleDetails: () => ipcRenderer.invoke('file:subtitle'),
  setWindowTheme: light => ipcRenderer.invoke('window:theme', Boolean(light)),
  setWindowButtons: mode => ipcRenderer.invoke('window:buttons', String(mode || 'page')),
  updateState: () => ipcRenderer.invoke('update:state'),
  checkUpdate: () => ipcRenderer.invoke('update:check'),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  onUpdateState: callback => ipcRenderer.on('update:state', (_, value) => callback(value)),
  tmdbKey: () => ipcRenderer.invoke('tmdb:get'),
  resolveTitles: list => ipcRenderer.invoke('titles:resolve', list),
  titleVariants: query => ipcRenderer.invoke('titles:variants', query),
  catalogKoreanSearch: (provider, query) => ipcRenderer.invoke('catalog:search-korean', provider, query),
  catalogIndexState: () => ipcRenderer.invoke('catalog-index:state'),
  activateCatalog: provider => ipcRenderer.invoke('catalog:activate', provider),
  onCatalogIndexState: callback => ipcRenderer.on('catalog-index:state', (_, value) => callback(value)),
  setTmdbKey: key => ipcRenderer.invoke('tmdb:set', key),
  geminiSettings: () => ipcRenderer.invoke('gemini:get'),
  setGeminiSettings: value => ipcRenderer.invoke('gemini:set', value),
  translateSubtitle: options => ipcRenderer.invoke('subtitle:translate', options),
  jimakuList: (anime, episode) => ipcRenderer.invoke('jimaku:list', anime, episode),
  jimakuDownload: (file, anime, episode) => ipcRenderer.invoke('jimaku:download', file, anime, episode),
  installLocalModel: id => ipcRenderer.invoke('localai:install', id),
  cancelLocalModelInstall: id => ipcRenderer.invoke('localai:cancel-install', id),
  addLocalModelFile: () => ipcRenderer.invoke('localai:add-file'),
  removeLocalModel: id => ipcRenderer.invoke('localai:remove', id),
  onLocalModelProgress: callback => ipcRenderer.on('localai:progress', (_, value) => callback(value)),
  cancelTranslation: id => ipcRenderer.invoke('subtitle:cancel', id),
  prepareEpisodeSubtitle: options => ipcRenderer.invoke('subtitle:prepare', options),
  onTranslateProgress: callback => ipcRenderer.on('translate:progress', (_, value) => callback(value)),
  defaultSubtitleFont: (choice, customPath) => ipcRenderer.invoke('font:default', choice, customPath),
  chooseFont: () => ipcRenderer.invoke('file:font'),
  updateNotes: () => ipcRenderer.invoke('update:notes'),
  openExternal: url => ipcRenderer.invoke('open:external', url)
});
