const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('lilac', {
  season: () => ipcRenderer.invoke('anime:season'),
  top: () => ipcRenderer.invoke('anime:top'),
  search: query => ipcRenderer.invoke('anime:search', query),
  detail: id => ipcRenderer.invoke('anime:detail', id),
  linkkfHome: (page = 1, limit = 20) => ipcRenderer.invoke('linkkf:home', page, limit),
  linkkfDetail: id => ipcRenderer.invoke('linkkf:detail', id),
  linkkfEpisodes: id => ipcRenderer.invoke('linkkf:episodes', id),
  linkkfPlay: episode => ipcRenderer.invoke('linkkf:play', episode),
  linkkfResolve: episode => ipcRenderer.invoke('linkkf:resolve', episode),
  linkkfSchedule: () => ipcRenderer.invoke('linkkf:schedule'),
  linkkfSections: () => ipcRenderer.invoke('linkkf:sections'),
  linkkfFilterTags: () => ipcRenderer.invoke('linkkf:filter-tags'),
  linkkfFilter: request => ipcRenderer.invoke('linkkf:filter', request),
  linkkfSearch: query => ipcRenderer.invoke('linkkf:search', query),
  linkkfExtras: anime => ipcRenderer.invoke('linkkf:extras', anime),
  linkkfRecordView: postId => ipcRenderer.invoke('linkkf:record-view', postId),
  providerCatalog: (provider, query = '', offset = 0) => ipcRenderer.invoke('provider:catalog', provider, query, offset),
  providerDetail: anime => ipcRenderer.invoke('provider:detail', anime),
  providerPlay: (episode, title) => ipcRenderer.invoke('provider:play', episode, title),
  providerResolve: episode => ipcRenderer.invoke('provider:resolve', episode),
  providerSubtitleTracks: episode => ipcRenderer.invoke('provider:subtitle-tracks', episode),
  coverData: url => ipcRenderer.invoke('cover:data', url),
  opEdSkip: request => ipcRenderer.invoke('oped:get', request),
  clearOpEd: () => ipcRenderer.invoke('oped:clear'),
  onOpEdStatus: callback => ipcRenderer.on('oped:status', (_, message) => callback(message)),
  downloadMedia: (url, name) => ipcRenderer.invoke('media:download', url, name),
  onDownloadProgress: callback => ipcRenderer.on('download:progress', (_, value) => callback(value)),
  downloads: () => ipcRenderer.invoke('downloads:list'),
  addDownload: request => ipcRenderer.invoke('downloads:add', request),
  cancelDownload: id => ipcRenderer.invoke('downloads:cancel', id),
  resumeDownload: id => ipcRenderer.invoke('downloads:resume', id),
  removeDownload: id => ipcRenderer.invoke('downloads:remove', id),
  playDownload: id => ipcRenderer.invoke('downloads:play', id),
  openDownloadsFolder: () => ipcRenderer.invoke('downloads:open-folder'),
  onDownloadsChanged: callback => ipcRenderer.on('downloads:changed', (_, value) => callback(value)),
  findSubtitle: (source, title, episode, anime) => ipcRenderer.invoke('subtitle:find', source, title, episode, anime),
  remoteSubtitle: (url, referer) => ipcRenderer.invoke('subtitle:remote', url, referer),
  savedSubtitles: key => ipcRenderer.invoke('subtitle-store:list', key),
  saveSubtitle: (key, entry) => ipcRenderer.invoke('subtitle-store:save', key, entry),
  removeSavedSubtitle: (key, id) => ipcRenderer.invoke('subtitle-store:remove', key, id),
  mpvStatus: () => ipcRenderer.invoke('mpv:status'),
  mpvPlay: (url, subtitlePath, title) => ipcRenderer.invoke('mpv:play', url, subtitlePath, title),
  setPlayerFullscreen: enabled => ipcRenderer.invoke('player:fullscreen', Boolean(enabled)),
  // Main returns {path,url}: url.pathToFileURL is unavailable in the sandboxed preload.
  chooseVideo: async () => (await ipcRenderer.invoke('file:video'))?.url || null,
  chooseSubtitle: async () => (await ipcRenderer.invoke('file:subtitle'))?.url || null,
  chooseSubtitleDetails: () => ipcRenderer.invoke('file:subtitle'),
  setWindowTheme: light => ipcRenderer.invoke('window:theme', Boolean(light)),
  updateState: () => ipcRenderer.invoke('update:state'),
  checkUpdate: () => ipcRenderer.invoke('update:check'),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  onUpdateState: callback => ipcRenderer.on('update:state', (_, value) => callback(value)),
  defaultSubtitleFont: (choice, customPath) => ipcRenderer.invoke('font:default', choice, customPath),
  chooseFont: () => ipcRenderer.invoke('file:font'),
  openExternal: url => ipcRenderer.invoke('open:external', url)
});
